//! End-to-end TITO merge tests against a **real** tokenizer.
//!
//! These tests load actual Qwen3 / Qwen3.5 tokenizers (the models used by the
//! mini-SWE PSRL runs) and verify that the incremental merge produced by
//! [`smg_tito::engine::TitoEngine`] — including multi-turn interleaving and the
//! compacted-context case where assistant turns appear in the appended slice —
//! is byte-correct with respect to the chat template's full one-shot render.
//!
//! The tokenizer directories are resolved from `SMG_QWEN3_TOKENIZER_DIR` /
//! `SMG_QWEN35_TOKENIZER_DIR`, falling back to the verl-cache locations present
//! on the training hosts.  If neither exists the tests are skipped (they are not
//! part of a hermetic CI build).

use std::{path::Path, sync::Arc};

use llm_tokenizer::{
    chat_template::ChatTemplateParams, create_tokenizer_with_chat_template, traits::Tokenizer,
};
use openai_protocol::chat::{ChatMessage, MessageContent};
use serde_json::json;
use smg_tito::{
    engine::TitoEngine,
    model_adapter::{select_adapter_for_tokenizer, ModelAdapter},
    normalizer::{hash_messages_with_context, RenderContext},
    store::TitoStore,
    validator::TokenSeqValidator,
    TurnRecord,
};

/// The run's custom template (no think stripping, per-message render).
const NO_THINK_STRIP_TEMPLATE: &str = r#"
{%- for message in messages %}
    {%- set content = message.content if message.content is string else '' %}
    {%- if message.role == 'system' or message.role == 'user' or message.role == 'assistant' %}
        {{- '<|im_start|>' + message.role + '\n' + content + '<|im_end|>\n' }}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n<think>\n\n</think>\n\n' }}
{%- endif %}
"#;

/// The position-independent Qwen3.5 patch (PSRL side:
/// `examples/mini_swe/config/qwen35_no_think_strip.jinja`): renders assistant
/// reasoning/content verbatim at every position, so the accumulated stream
/// equals a fresh one-shot render.  Mirrors the file generated by
/// `config/gen_qwen35_no_think_strip.py`.
const QWEN35_NO_THINK_STRIP_TEMPLATE: &str = r##"{%- set image_count = namespace(value=0) %}
{%- set video_count = namespace(value=0) %}
{%- macro render_content(content, do_vision_count, is_system_content=false) %}
    {%- if content is string %}
        {{- content }}
    {%- elif content is iterable and content is not mapping %}
        {%- for item in content %}
            {%- if 'image' in item or 'image_url' in item or item.type == 'image' %}
                {%- if is_system_content %}
                    {{- raise_exception('System message cannot contain images.') }}
                {%- endif %}
                {%- if do_vision_count %}
                    {%- set image_count.value = image_count.value + 1 %}
                {%- endif %}
                {%- if add_vision_id %}
                    {{- 'Picture ' ~ image_count.value ~ ': ' }}
                {%- endif %}
                {{- '<|vision_start|><|image_pad|><|vision_end|>' }}
            {%- elif 'video' in item or item.type == 'video' %}
                {%- if is_system_content %}
                    {{- raise_exception('System message cannot contain videos.') }}
                {%- endif %}
                {%- if do_vision_count %}
                    {%- set video_count.value = video_count.value + 1 %}
                {%- endif %}
                {%- if add_vision_id %}
                    {{- 'Video ' ~ video_count.value ~ ': ' }}
                {%- endif %}
                {{- '<|vision_start|><|video_pad|><|vision_end|>' }}
            {%- elif 'text' in item %}
                {{- item.text }}
            {%- else %}
                {{- raise_exception('Unexpected item type in content.') }}
            {%- endif %}
        {%- endfor %}
    {%- elif content is none or content is undefined %}
        {{- '' }}
    {%- else %}
        {{- raise_exception('Unexpected content type.') }}
    {%- endif %}
{%- endmacro %}
{%- if not messages %}
    {{- raise_exception('No messages provided.') }}
{%- endif %}
{%- if tools and tools is iterable and tools is not mapping %}
    {{- '<|im_start|>system\n' }}
    {{- "# Tools\n\nYou have access to the following functions:\n\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>" }}
    {{- '\n\nIf you choose to call a function ONLY reply in the following format with NO suffix:\n\n<tool_call>\n<function=example_function_name>\n<parameter=example_parameter_1>\nvalue_1\n</parameter>\n<parameter=example_parameter_2>\nThis is the value for the second parameter\nthat can span\nmultiple lines\n</parameter>\n</function>\n</tool_call>\n\n<IMPORTANT>\nReminder:\n- Function calls MUST follow the specified format: an inner <function=...></function> block must be nested within <tool_call></tool_call> XML tags\n- Required parameters MUST be specified\n- You may provide optional reasoning for your function call in natural language BEFORE the function call, but NOT after\n- If there is no function call available, answer the question like normal with your current knowledge and do not tell the user about function calls\n</IMPORTANT>' }}
    {%- if messages[0].role == 'system' %}
        {%- set content = render_content(messages[0].content, false, true)|trim %}
        {%- if content %}
            {{- '\n\n' + content }}
        {%- endif %}
    {%- endif %}
    {{- '<|im_end|>\n' }}
{%- else %}
    {%- if messages[0].role == 'system' %}
        {%- set content = render_content(messages[0].content, false, true)|trim %}
        {{- '<|im_start|>system\n' + content + '<|im_end|>\n' }}
    {%- endif %}
{%- endif %}

{%- for message in messages %}
    {%- set content = render_content(message.content, true)|trim %}
    {%- if message.role == "system" %}
        {%- if not loop.first %}
            {{- raise_exception('System message must be at the beginning.') }}
        {%- endif %}
    {%- elif message.role == "user" %}
        {{- '<|im_start|>' + message.role + '\n' + content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {%- set reasoning_content = '' %}
        {%- if message.reasoning_content is string %}
            {%- set reasoning_content = message.reasoning_content %}
        {%- else %}
            {%- if '</think>' in content %}
                {%- set reasoning_content = content.split('</think>')[0].rstrip('\n').split('<think>')[-1].lstrip('\n') %}
                {%- set content = content.split('</think>')[-1].lstrip('\n') %}
            {%- endif %}
        {%- endif %}
        {%- set reasoning_content = reasoning_content|trim %}
        {{- '<|im_start|>' + message.role + '\n' }}
        {%- if reasoning_content %}
            {{- '<think>\n' + reasoning_content + '\n</think>\n\n' }}
        {%- endif %}
        {{- content }}
        {%- if message.tool_calls and message.tool_calls is iterable and message.tool_calls is not mapping %}
            {%- for tool_call in message.tool_calls %}
                {%- if tool_call.function is defined %}
                    {%- set tool_call = tool_call.function %}
                {%- endif %}
                {%- if loop.first %}
                    {%- if content|trim %}
                        {{- '\n\n<tool_call>\n<function=' + tool_call.name + '>\n' }}
                    {%- else %}
                        {{- '<tool_call>\n<function=' + tool_call.name + '>\n' }}
                    {%- endif %}
                {%- else %}
                    {{- '\n<tool_call>\n<function=' + tool_call.name + '>\n' }}
                {%- endif %}
                {%- if tool_call.arguments is defined %}
                    {%- for args_name, args_value in tool_call.arguments|items %}
                        {{- '<parameter=' + args_name + '>\n' }}
                        {%- set args_value = args_value | tojson | safe if args_value is mapping or (args_value is sequence and args_value is not string) else args_value | string %}
                        {{- args_value }}
                        {{- '\n</parameter>\n' }}
                    {%- endfor %}
                {%- endif %}
                {{- '</function>\n</tool_call>' }}
            {%- endfor %}
        {%- endif %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if loop.previtem and loop.previtem.role != "tool" %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- content }}
        {{- '\n</tool_response>' }}
        {%- if not loop.last and loop.nextitem.role != "tool" %}
            {{- '<|im_end|>\n' }}
        {%- elif loop.last %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- else %}
        {{- raise_exception('Unexpected message role.') }}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
    {%- if enable_thinking is defined and enable_thinking is false %}
        {{- '<think>\n\n</think>\n\n' }}
    {%- else %}
        {{- '<think>\n' }}
    {%- endif %}
{%- endif %}"##;
fn real_qwen3_dir() -> Option<String> {
    let candidates = [
        std::env::var("SMG_QWEN3_TOKENIZER_DIR").ok(),
        Some(
            "/dev/shm/verl-cache/142bc806fb2a1653e8221c7bedce85e4/Qwen3-4B-Instruct-2507"
                .to_string(),
        ),
    ];
    candidates
        .into_iter()
        .flatten()
        .find(|p| Path::new(p).join("tokenizer.json").exists())
}

/// Load the real Qwen3 tokenizer. `template_override`: if `Some`, the template
/// text is written to a temp file and passed as the chat template; if `None`,
/// the model's own chat template (from tokenizer_config.json) is used.
fn load_qwen3_tokenizer(template_override: Option<&str>) -> Option<Arc<dyn Tokenizer>> {
    let dir = real_qwen3_dir()?;
    let template_path = match template_override {
        Some(template) => {
            let mut f = tempfile::NamedTempFile::new().ok()?;
            std::io::Write::write_all(&mut f, template.as_bytes()).ok()?;
            Some(f.path().to_str().unwrap().to_string())
        }
        None => None,
    };
    create_tokenizer_with_chat_template(&dir, template_path.as_deref()).ok()
}

fn real_qwen35_dir() -> Option<String> {
    let candidates = [
        std::env::var("SMG_QWEN35_TOKENIZER_DIR").ok(),
        Some("/dev/shm/verl-cache/a797e758042926a7803e6ad6e5de7812/Qwen3.5-4B".to_string()),
    ];
    candidates
        .into_iter()
        .flatten()
        .find(|p| Path::new(p).join("tokenizer.json").exists())
}

/// Load the real Qwen3.5 tokenizer with its own (position-dependent) chat template.
fn load_qwen35_tokenizer() -> Option<Arc<dyn Tokenizer>> {
    let dir = real_qwen35_dir()?;
    create_tokenizer_with_chat_template(&dir, None).ok()
}

/// Load the real Qwen3.5 tokenizer with an explicit template (e.g. the patched
/// position-independent one).  SMG does not own model-specific template patches;
/// the deployment layer supplies them via `chat_template_path`, which the test
/// mirrors by staging the template to a temp file.
fn load_qwen35_tokenizer_with_template(template: &str) -> Option<Arc<dyn Tokenizer>> {
    let dir = real_qwen35_dir()?;
    let mut f = tempfile::NamedTempFile::new().ok()?;
    std::io::Write::write_all(&mut f, template.as_bytes()).ok()?;
    create_tokenizer_with_chat_template(&dir, f.path().to_str()).ok()
}

fn render(
    tokenizer: &dyn Tokenizer,
    messages: &[ChatMessage],
    ctx: &RenderContext,
    add_generation_prompt: bool,
) -> String {
    // All test messages use plain-text content, so no content-field transform
    // is needed; serialize each message directly.
    let values: Vec<serde_json::Value> = messages
        .iter()
        .map(|m| serde_json::to_value(m).unwrap())
        .collect();
    tokenizer
        .apply_chat_template(
            &values,
            ChatTemplateParams {
                add_generation_prompt,
                tools: ctx.tools_ref(),
                template_kwargs: ctx.template_kwargs_ref(),
                ..Default::default()
            },
        )
        .unwrap()
}

fn encode(tokenizer: &dyn Tokenizer, text: &str) -> Vec<u32> {
    tokenizer.encode(text, false).unwrap().token_ids().to_vec()
}

fn decode(tokenizer: &dyn Tokenizer, ids: &[u32]) -> String {
    tokenizer.decode(ids, false).unwrap()
}

fn user_msg(content: &str) -> ChatMessage {
    ChatMessage::User {
        content: MessageContent::Text(content.to_string()),
        name: None,
    }
}

fn assistant_msg(content: &str) -> ChatMessage {
    ChatMessage::Assistant {
        content: Some(MessageContent::Text(content.to_string())),
        name: None,
        tool_calls: None,
        reasoning_content: None,
    }
}

fn assistant_tool_call_msg(
    content: Option<&str>,
    tool_call_id: &str,
    fn_name: &str,
) -> ChatMessage {
    use openai_protocol::common::{FunctionCallResponse, ToolCall};
    ChatMessage::Assistant {
        content: content.map(|c| MessageContent::Text(c.to_string())),
        name: None,
        reasoning_content: None,
        tool_calls: Some(vec![ToolCall {
            id: tool_call_id.to_string(),
            tool_type: "function".to_string(),
            function: FunctionCallResponse {
                name: fn_name.to_string(),
                arguments: Some("{}".to_string()),
            },
        }]),
    }
}

fn tool_msg(content: &str, call_id: &str) -> ChatMessage {
    ChatMessage::Tool {
        content: MessageContent::Text(content.to_string()),
        tool_call_id: call_id.to_string(),
    }
}

fn record(prompt_token_count: usize) -> TurnRecord {
    TurnRecord {
        prompt_token_count,
        output_logprobs: None,
        finish_reason: "stop".to_string(),
        mismatch_report: vec![],
        routed_experts: None,
        weight_version: None,
    }
}

fn render_context() -> RenderContext {
    RenderContext::new(None, None)
}

/// Validate that no TITO violation (non-assistant / structural mismatch) exists
/// between the merged token stream and the canonical full render.
fn assert_no_tito_violation(
    tokenizer: &Arc<dyn Tokenizer>,
    full_ids: &[u32],
    all_messages: &[ChatMessage],
    ctx: &RenderContext,
    adapter: &dyn ModelAdapter,
    label: &str,
) {
    let special: std::collections::HashSet<u32> =
        adapter.trailing_token_ids().iter().copied().collect();
    let validator = TokenSeqValidator::new(
        Arc::clone(tokenizer),
        adapter.assistant_start_str().map(String::from),
        special,
    );
    let mismatches = validator.validate(full_ids, all_messages, false, None, ctx);
    let violations: Vec<_> = mismatches
        .iter()
        .filter(|m| m.mismatch_type != "assistant_text")
        .collect();
    assert!(
        violations.is_empty(),
        "[{label}] TITO violations detected: {violations:#?}",
    );
}

/// Simulate one generation turn: returns the `full_ids` (prompt + output) that
/// production would store, plus the assistant message that gets hashed into the
/// prefix tree.
///
/// The model generates after the generation prompt and terminates its turn with
/// the EOS `<|im_end|>` token, so `output_text` is encoded with a trailing
/// `<|im_end|>` (mirroring the raw output stored in the accumulated sequence).
fn simulate_generation(
    tokenizer: &dyn Tokenizer,
    request_messages: &[ChatMessage],
    ctx: &RenderContext,
    output_text: &str,
) -> (Vec<u32>, ChatMessage) {
    let prompt_ids = encode(tokenizer, &render(tokenizer, request_messages, ctx, true));
    let output_ids = encode(tokenizer, &format!("{output_text}<|im_end|>"));
    let mut full_ids = prompt_ids;
    full_ids.extend_from_slice(&output_ids);
    (full_ids, assistant_msg(output_text))
}

/// Assistant message carrying a separate reasoning (`<think>`) block.
fn assistant_reasoning_msg(think: &str, answer: &str) -> ChatMessage {
    ChatMessage::Assistant {
        content: Some(MessageContent::Text(answer.to_string())),
        name: None,
        reasoning_content: Some(think.to_string()),
        tool_calls: None,
    }
}

/// Simulate a thinking-model generation turn: the model continues the
/// generation prompt's `<think>` prefill, writes its reasoning, closes
/// `</think>`, then answers and emits `<|im_end|>`.
fn simulate_generation_thinking(
    tokenizer: &dyn Tokenizer,
    request_messages: &[ChatMessage],
    ctx: &RenderContext,
    think: &str,
    answer: &str,
) -> (Vec<u32>, ChatMessage) {
    let prompt_ids = encode(tokenizer, &render(tokenizer, request_messages, ctx, true));
    let output_ids = encode(
        tokenizer,
        &format!("{think}\n</think>\n\n{answer}<|im_end|>"),
    );
    let mut full_ids = prompt_ids;
    full_ids.extend_from_slice(&output_ids);
    (full_ids, assistant_reasoning_msg(think, answer))
}

#[test]
fn real_qwen3_multiturn_merge_matches_full_render() {
    let Some(tokenizer) = load_qwen3_tokenizer(None) else {
        eprintln!("SKIP: real Qwen3 tokenizer not found");
        return;
    };
    let ctx = render_context();
    let adapter = select_adapter_for_tokenizer(&*tokenizer).unwrap();
    let store = TitoStore::new();
    store.create_session("s1");

    let system = ChatMessage::System {
        content: MessageContent::Text("You are a coding agent.\nSolve the task.".to_string()),
        name: None,
    };
    let user1 = user_msg("Inspect the repo.");
    let turn0_req = vec![system.clone(), user1.clone()];
    let (turn0_full, assistant1) =
        simulate_generation(&*tokenizer, &turn0_req, &ctx, "Let me look around.");
    store
        .store(
            "s1",
            &[system.clone(), user1.clone(), assistant1.clone()],
            turn0_full.clone(),
            record(turn0_full.len()),
            &ctx,
            0,
        )
        .unwrap();

    let turn1_req = vec![
        system.clone(),
        user1.clone(),
        assistant1.clone(),
        tool_msg("repo has src/main.py", "call_1"),
        user_msg("Fix the bug in src/main.py."),
    ];
    let lookup = store
        .find_prefix_with_lookup("s1", &turn1_req, &ctx)
        .unwrap();
    let pm = lookup.matched.expect("expected a prefix HIT on turn 1");
    assert_eq!(pm.matched_message_num, 3);

    let appended = &turn1_req[pm.matched_message_num..];
    let merged =
        TitoEngine::merge_incremental(pm, appended, &*tokenizer, &*adapter, &ctx, None).unwrap();

    let mut full_ids = merged;
    full_ids.extend(encode(
        &*tokenizer,
        "I found the bug and fixed it.<|im_end|>",
    ));

    let mut all_messages = turn1_req;
    all_messages.push(assistant_msg("I found the bug and fixed it."));
    assert_no_tito_violation(
        &tokenizer,
        &full_ids,
        &all_messages,
        &ctx,
        &*adapter,
        "multi-turn",
    );
}

#[test]
fn real_qwen3_compressed_context_assistant_in_appended_matches_full_render() {
    let Some(tokenizer) = load_qwen3_tokenizer(None) else {
        eprintln!("SKIP: real Qwen3 tokenizer not found");
        return;
    };
    let ctx = render_context();
    let adapter = select_adapter_for_tokenizer(&*tokenizer).unwrap();

    let store = TitoStore::new();
    store.create_session("s1");

    let system = ChatMessage::System {
        content: MessageContent::Text("You are a coding agent.\nSolve the task.".to_string()),
        name: None,
    };
    let user1 = user_msg("Inspect the repo.");
    let (turn0_full, assistant1) = simulate_generation(
        &*tokenizer,
        &[system.clone(), user1.clone()],
        &ctx,
        "Let me look around.",
    );
    store
        .store(
            "s1",
            &[system.clone(), user1.clone(), assistant1.clone()],
            turn0_full.clone(),
            record(turn0_full.len()),
            &ctx,
            0,
        )
        .unwrap();

    // Compaction scenario: the request re-injects an assistant turn inside the
    // appended slice (as Claude Code auto-compact would) — the appended slice
    // is [tool, user2, assistant(compacted), user3].
    let turn2_req = vec![
        system.clone(),
        user1.clone(),
        assistant1.clone(),
        tool_msg("repo has src/main.py", "call_1"),
        user_msg("Fix the bug in src/main.py."),
        assistant_msg("(compacted summary of my earlier progress)"),
        user_msg("Now apply the fix."),
    ];
    let lookup = store
        .find_prefix_with_lookup("s1", &turn2_req, &ctx)
        .unwrap();
    let pm = lookup.matched.expect("expected a prefix HIT on turn 2");
    assert_eq!(pm.matched_message_num, 3);

    let appended = &turn2_req[pm.matched_message_num..];
    assert!(
        appended
            .iter()
            .any(|m| matches!(m, ChatMessage::Assistant { .. })),
        "test must exercise the assistant-in-appended path"
    );
    let merged =
        TitoEngine::merge_incremental(pm, appended, &*tokenizer, &*adapter, &ctx, None).unwrap();

    let mut full_ids = merged;
    full_ids.extend(encode(&*tokenizer, "Fix applied.<|im_end|>"));
    let mut all_messages = turn2_req;
    all_messages.push(assistant_msg("Fix applied."));
    assert_no_tito_violation(
        &tokenizer,
        &full_ids,
        &all_messages,
        &ctx,
        &*adapter,
        "compressed-context",
    );
}

#[test]
fn real_qwen3_compressed_context_with_tool_call_assistant_matches_full_render() {
    // The appended slice carries a compacted assistant turn that itself issued a
    // tool call, followed by its tool response.  This exercises the assistant
    // tool-call rendering path of the incremental merge (per-message dependent
    // in Qwen3) as well as the tool segment right after it.
    let Some(tokenizer) = load_qwen3_tokenizer(None) else {
        eprintln!("SKIP: real Qwen3 tokenizer not found");
        return;
    };
    let ctx = render_context();
    let adapter = select_adapter_for_tokenizer(&*tokenizer).unwrap();

    let store = TitoStore::new();
    store.create_session("s1");

    let system = ChatMessage::System {
        content: MessageContent::Text("You are a coding agent.\nSolve the task.".to_string()),
        name: None,
    };
    let user1 = user_msg("Inspect the repo.");
    let (turn0_full, assistant1) = simulate_generation(
        &*tokenizer,
        &[system.clone(), user1.clone()],
        &ctx,
        "Let me look around.",
    );
    store
        .store(
            "s1",
            &[system.clone(), user1.clone(), assistant1.clone()],
            turn0_full.clone(),
            record(turn0_full.len()),
            &ctx,
            0,
        )
        .unwrap();

    let turn2_req = vec![
        system.clone(),
        user1.clone(),
        assistant1.clone(),
        assistant_tool_call_msg(Some("Let me run the test suite."), "call_2", "Bash"),
        tool_msg("tests passed", "call_2"),
        user_msg("Great, now commit."),
    ];
    let lookup = store
        .find_prefix_with_lookup("s1", &turn2_req, &ctx)
        .unwrap();
    let pm = lookup.matched.expect("expected a prefix HIT");
    assert_eq!(pm.matched_message_num, 3);
    let appended = &turn2_req[pm.matched_message_num..];
    assert!(appended
        .iter()
        .any(|m| matches!(m, ChatMessage::Assistant { .. })));

    let merged =
        TitoEngine::merge_incremental(pm, appended, &*tokenizer, &*adapter, &ctx, None).unwrap();
    let mut full_ids = merged;
    full_ids.extend(encode(&*tokenizer, "Committed.<|im_end|>"));
    let mut all_messages = turn2_req;
    all_messages.push(assistant_msg("Committed."));
    assert_no_tito_violation(
        &tokenizer,
        &full_ids,
        &all_messages,
        &ctx,
        &*adapter,
        "tool-call compressed",
    );
}

#[test]
fn real_qwen3_no_think_strip_compressed_context_matches_full_render() {
    let Some(tokenizer) = load_qwen3_tokenizer(Some(NO_THINK_STRIP_TEMPLATE)) else {
        eprintln!("SKIP: real Qwen3 tokenizer not found");
        return;
    };
    let ctx = render_context();
    let adapter = select_adapter_for_tokenizer(&*tokenizer).unwrap();

    let store = TitoStore::new();
    store.create_session("s1");

    let system = ChatMessage::System {
        content: MessageContent::Text("You are a coding agent.\nSolve the task.".to_string()),
        name: None,
    };
    let user1 = user_msg("Inspect the repo.");
    let (turn0_full, assistant1) = simulate_generation(
        &*tokenizer,
        &[system.clone(), user1.clone()],
        &ctx,
        "Let me look around.",
    );
    store
        .store(
            "s1",
            &[system.clone(), user1.clone(), assistant1.clone()],
            turn0_full.clone(),
            record(turn0_full.len()),
            &ctx,
            0,
        )
        .unwrap();

    let turn2_req = vec![
        system.clone(),
        user1.clone(),
        assistant1.clone(),
        tool_msg("repo has src/main.py", "call_1"),
        user_msg("Fix the bug in src/main.py."),
        assistant_msg("(compacted summary)"),
        user_msg("Now apply the fix."),
    ];
    let lookup = store
        .find_prefix_with_lookup("s1", &turn2_req, &ctx)
        .unwrap();
    let pm = lookup.matched.expect("expected a prefix HIT");
    assert_eq!(pm.matched_message_num, 3);

    let appended = &turn2_req[pm.matched_message_num..];
    let merged =
        TitoEngine::merge_incremental(pm, appended, &*tokenizer, &*adapter, &ctx, None).unwrap();

    let mut full_ids = merged;
    full_ids.extend(encode(&*tokenizer, "Fix applied.<|im_end|>"));
    let mut all_messages = turn2_req;
    all_messages.push(assistant_msg("Fix applied."));
    assert_no_tito_violation(
        &tokenizer,
        &full_ids,
        &all_messages,
        &ctx,
        &*adapter,
        "no-think-strip compressed",
    );
}

#[test]
fn tools_key_order_change_must_invalidate_render_context_hash() {
    // Regression test for the stale-prefix bug: the render_context hash used to
    // canonicalize (sort) tools, but the chat template renders `tools | tojson`
    // in native key order.  A request whose tools JSON key order changes between
    // turns therefore re-used a stale prefix whose rendered system header
    // diverged from the current render (the validator's `non_assistant_text`
    // position-1 error).  The hash must be order-sensitive.
    let tools_a = vec![json!({
        "type": "function",
        "function": {
            "name": "Bash",
            "parameters": {
                "type": "object",
                "properties": {
                    "command": {"type": "string"},
                    "timeout": {"type": "number"},
                    "description": {"type": "string"}
                },
                "required": ["command"]
            }
        }
    })];
    let tools_b = vec![json!({
        "type": "function",
        "function": {
            "name": "Bash",
            "parameters": {
                "type": "object",
                "properties": {
                    "description": {"type": "string"},
                    "timeout": {"type": "number"},
                    "command": {"type": "string"}
                },
                "required": ["command"]
            }
        }
    })];

    let ctx_a = RenderContext::new(Some(tools_a), None);
    let ctx_b = RenderContext::new(Some(tools_b), None);
    let messages = vec![ChatMessage::System {
        content: MessageContent::Text("You are a coding agent.".to_string()),
        name: None,
    }];

    let hash_a = hash_messages_with_context(&messages, &ctx_a);
    let hash_b = hash_messages_with_context(&messages, &ctx_b);
    assert_ne!(
        hash_a, hash_b,
        "tools key-order change must invalidate the render_context hash"
    );

    // And the renders must differ accordingly (native order preserved).
    let Some(tokenizer) = load_qwen3_tokenizer(None) else {
        eprintln!("SKIP: real Qwen3 tokenizer not found");
        return;
    };
    let text_a = render(&*tokenizer, &messages, &ctx_a, false);
    let text_b = render(&*tokenizer, &messages, &ctx_b, false);
    assert_ne!(
        text_a, text_b,
        "tools key-order must change the rendered header"
    );
}

#[test]
fn real_qwen35_compressed_context_uses_whole_slice_path() {
    // Qwen3.5's stock template is position-dependent: an assistant turn is
    // wrapped in `<think>` only when it appears after the last real user query
    // (`ns.last_query_index`).  The engine must therefore take the whole-slice
    // single-pass path (`[dummy_system, dummy_user]` base) instead of per-message
    // dummy bases.  The whole-slice path is translation-invariant: the appended
    // messages render with the same wrap/tool decisions as the production
    // context, for BOTH the stock template and the patched position-independent
    // one.  This test runs against the stock template and verifies the merged
    // incremental byte-for-byte against the production slice render.
    //
    // Note: the TITO validator cannot be used here — the stock template
    // re-evaluates the `<think>` wrap of past turns from the final message
    // list, so the accumulated stream and a one-shot render never align.
    let Some(tokenizer) = load_qwen35_tokenizer() else {
        eprintln!("SKIP: real Qwen3.5 tokenizer not found");
        return;
    };
    let ctx = render_context();
    let adapter = select_adapter_for_tokenizer(&*tokenizer).unwrap();
    assert!(
        tokenizer.chat_template_is_position_dependent(),
        "stock Qwen3.5 template must use the whole-slice path"
    );

    let store = TitoStore::new();
    store.create_session("s1");

    let system = ChatMessage::System {
        content: MessageContent::Text("You are a coding agent.\nSolve the task.".to_string()),
        name: None,
    };
    let user1 = user_msg("Inspect the repo.");
    let (turn0_full, assistant1) = simulate_generation(
        &*tokenizer,
        &[system.clone(), user1.clone()],
        &ctx,
        "Let me look around.",
    );
    store
        .store(
            "s1",
            &[system.clone(), user1.clone(), assistant1.clone()],
            turn0_full.clone(),
            record(turn0_full.len()),
            &ctx,
            0,
        )
        .unwrap();

    let turn2_req = vec![
        system.clone(),
        user1.clone(),
        assistant1.clone(),
        assistant_msg("I checked the failing test."),
        tool_msg("tests: 1 failed", "call_1"),
        user_msg("Fix the failing test."),
        assistant_msg("(compacted plan: patch the assertion)"),
    ];
    let lookup = store
        .find_prefix_with_lookup("s1", &turn2_req, &ctx)
        .unwrap();
    let pm = lookup.matched.expect("expected a prefix HIT");
    assert_eq!(pm.matched_message_num, 3);
    let appended = &turn2_req[pm.matched_message_num..];
    assert!(appended
        .iter()
        .any(|m| matches!(m, ChatMessage::Assistant { .. })));
    let stored_prefix_ids = pm.pretokenized_ids.clone();

    let merged =
        TitoEngine::merge_incremental(pm, appended, &*tokenizer, &*adapter, &ctx, None).unwrap();

    // The whole-slice incremental (after the adjusted prefix) must equal the
    // production render of the appended slice (+ the generation prompt)
    // relative to the user prefix — under the stock position-dependent template.
    let mut prod_all = vec![system.clone(), user1.clone()];
    prod_all.extend_from_slice(appended);
    let prod_base_text = render(&*tokenizer, &[system.clone(), user1.clone()], &ctx, false);
    let prod_full_text = render(&*tokenizer, &prod_all, &ctx, true);
    assert!(prod_full_text.starts_with(&prod_base_text));
    let prod_tail = &prod_full_text[prod_base_text.len()..];

    let adjusted_prefix = adapter.adjust_prefix_boundary(&stored_prefix_ids);
    let incremental_ids = &merged[adjusted_prefix.len()..];
    let incremental_text = decode(&*tokenizer, incremental_ids);
    assert_eq!(
        incremental_text, prod_tail,
        "whole-slice incremental must equal the production slice render"
    );
}

#[test]
fn real_qwen35_patched_template_validator_ok() {
    // With the position-independent patch (PSRL side
    // `examples/mini_swe/config/qwen35_no_think_strip.jinja`) the fresh one-shot
    // render equals the accumulated stream for a *thinking* model (the generation
    // prompt prefills `<think>` and the model continues it), so the TITO
    // validator is usable again and must find no violations.
    let Some(tokenizer) = load_qwen35_tokenizer_with_template(QWEN35_NO_THINK_STRIP_TEMPLATE)
    else {
        eprintln!("SKIP: real Qwen3.5 tokenizer not found");
        return;
    };
    let ctx = render_context();
    let adapter = select_adapter_for_tokenizer(&*tokenizer).unwrap();
    assert!(
        !tokenizer.chat_template_is_position_dependent(),
        "patched Qwen3.5 template must use the segment path"
    );

    let store = TitoStore::new();
    store.create_session("s1");

    let system = ChatMessage::System {
        content: MessageContent::Text("You are a coding agent.\nSolve the task.".to_string()),
        name: None,
    };
    let user1 = user_msg("Inspect the repo.");
    let (turn0_full, assistant1) = simulate_generation_thinking(
        &*tokenizer,
        &[system.clone(), user1.clone()],
        &ctx,
        "I should inspect the repo first.",
        "Let me look around.",
    );
    store
        .store(
            "s1",
            &[system.clone(), user1.clone(), assistant1.clone()],
            turn0_full.clone(),
            record(turn0_full.len()),
            &ctx,
            0,
        )
        .unwrap();

    let turn2_req = vec![
        system.clone(),
        user1.clone(),
        assistant1.clone(),
        assistant_msg("I checked the failing test."),
        tool_msg("tests: 1 failed", "call_1"),
        user_msg("Fix the failing test."),
        assistant_msg("(compacted plan: patch the assertion)"),
    ];
    let lookup = store
        .find_prefix_with_lookup("s1", &turn2_req, &ctx)
        .unwrap();
    let pm = lookup.matched.expect("expected a prefix HIT");
    assert_eq!(pm.matched_message_num, 3);
    let appended = &turn2_req[pm.matched_message_num..];
    assert!(appended
        .iter()
        .any(|m| matches!(m, ChatMessage::Assistant { .. })));

    let merged =
        TitoEngine::merge_incremental(pm, appended, &*tokenizer, &*adapter, &ctx, None).unwrap();

    let mut full_ids = merged;
    full_ids.extend(encode(
        &*tokenizer,
        "I'll write the patch.\n</think>\n\nPatch applied.<|im_end|>",
    ));
    let mut all_messages = turn2_req;
    all_messages.push(assistant_reasoning_msg(
        "I'll write the patch.",
        "Patch applied.",
    ));
    assert_no_tito_violation(
        &tokenizer,
        &full_ids,
        &all_messages,
        &ctx,
        &*adapter,
        "qwen3.5 patched-template validator",
    );
}

#[test]
fn qwen35_patched_template_is_position_independent() {
    // Load the patched Qwen3.5 template explicitly (PSRL side supplies it via
    // `chat_template_path`; SMG does not own model-specific patches).  Verify
    // the core property of Plan A: appending a later user query after an
    // assistant turn must NOT change how that assistant renders (the stock
    // template would re-evaluate its `<think>` wrap and strip it).
    let Some(tokenizer) = load_qwen35_tokenizer_with_template(QWEN35_NO_THINK_STRIP_TEMPLATE)
    else {
        eprintln!("SKIP: real Qwen3.5 tokenizer not found");
        return;
    };
    let ctx = render_context();

    let system = ChatMessage::System {
        content: MessageContent::Text("You are a coding agent.\nSolve the task.".to_string()),
        name: None,
    };
    let user1 = user_msg("Inspect the repo.");
    let assistant = assistant_reasoning_msg("I should inspect.", "Let me look around.");

    let before = vec![system.clone(), user1.clone(), assistant.clone()];
    let after = vec![
        system.clone(),
        user1.clone(),
        assistant.clone(),
        user_msg("Now fix it."),
    ];
    let before_text = render(&*tokenizer, &before, &ctx, false);
    let after_text = render(&*tokenizer, &after, &ctx, false);
    assert!(
        after_text.starts_with(&before_text),
        "patched template must render the assistant identically regardless of position"
    );
    // The assistant's reasoning block must be present in both renders.
    assert!(before_text.contains("<think>"));
}
