// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: sglang_scheduler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SglangScheduler_Generate_FullMethodName          = "/sglang.grpc.scheduler.SglangScheduler/Generate"
	SglangScheduler_Embed_FullMethodName             = "/sglang.grpc.scheduler.SglangScheduler/Embed"
	SglangScheduler_HealthCheck_FullMethodName       = "/sglang.grpc.scheduler.SglangScheduler/HealthCheck"
	SglangScheduler_Abort_FullMethodName             = "/sglang.grpc.scheduler.SglangScheduler/Abort"
	SglangScheduler_GetModelInfo_FullMethodName      = "/sglang.grpc.scheduler.SglangScheduler/GetModelInfo"
	SglangScheduler_GetServerInfo_FullMethodName     = "/sglang.grpc.scheduler.SglangScheduler/GetServerInfo"
	SglangScheduler_GetLoads_FullMethodName          = "/sglang.grpc.scheduler.SglangScheduler/GetLoads"
	SglangScheduler_FlushCache_FullMethodName        = "/sglang.grpc.scheduler.SglangScheduler/FlushCache"
	SglangScheduler_StartProfile_FullMethodName      = "/sglang.grpc.scheduler.SglangScheduler/StartProfile"
	SglangScheduler_StopProfile_FullMethodName       = "/sglang.grpc.scheduler.SglangScheduler/StopProfile"
	SglangScheduler_GetTokenizer_FullMethodName      = "/sglang.grpc.scheduler.SglangScheduler/GetTokenizer"
	SglangScheduler_SubscribeKvEvents_FullMethodName = "/sglang.grpc.scheduler.SglangScheduler/SubscribeKvEvents"
)

// SglangSchedulerClient is the client API for SglangScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for SGLang scheduler communication
// This protocol bridges the Rust router and Python scheduler
type SglangSchedulerClient interface {
	// Submit a generation request (supports streaming)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error)
	// Submit an embedding request
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// Health check and metrics
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Abort a running request
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error)
	// Get model information
	GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error)
	// Get server information
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
	// Get comprehensive load metrics
	GetLoads(ctx context.Context, in *GetLoadsRequest, opts ...grpc.CallOption) (*GetLoadsResponse, error)
	// Flush the KV cache on all scheduler processes
	FlushCache(ctx context.Context, in *FlushCacheRequest, opts ...grpc.CallOption) (*FlushCacheResponse, error)
	// Start the profiler on all scheduler processes
	StartProfile(ctx context.Context, in *StartProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	// Stop the profiler and export traces
	StopProfile(ctx context.Context, in *StopProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	// Get tokenizer artifacts for remote construction
	GetTokenizer(ctx context.Context, in *GetTokenizerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTokenizerChunk], error)
	// Subscribe to KV cache events (server-streaming)
	SubscribeKvEvents(ctx context.Context, in *SubscribeKvEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KvEventBatch], error)
}

type sglangSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSglangSchedulerClient(cc grpc.ClientConnInterface) SglangSchedulerClient {
	return &sglangSchedulerClient{cc}
}

func (c *sglangSchedulerClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SglangScheduler_ServiceDesc.Streams[0], SglangScheduler_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SglangScheduler_GenerateClient = grpc.ServerStreamingClient[GenerateResponse]

func (c *sglangSchedulerClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelInfoResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_GetModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) GetLoads(ctx context.Context, in *GetLoadsRequest, opts ...grpc.CallOption) (*GetLoadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoadsResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_GetLoads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) FlushCache(ctx context.Context, in *FlushCacheRequest, opts ...grpc.CallOption) (*FlushCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushCacheResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_FlushCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) StartProfile(ctx context.Context, in *StartProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_StartProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) StopProfile(ctx context.Context, in *StopProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, SglangScheduler_StopProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sglangSchedulerClient) GetTokenizer(ctx context.Context, in *GetTokenizerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTokenizerChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SglangScheduler_ServiceDesc.Streams[1], SglangScheduler_GetTokenizer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetTokenizerRequest, GetTokenizerChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SglangScheduler_GetTokenizerClient = grpc.ServerStreamingClient[GetTokenizerChunk]

func (c *sglangSchedulerClient) SubscribeKvEvents(ctx context.Context, in *SubscribeKvEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KvEventBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SglangScheduler_ServiceDesc.Streams[2], SglangScheduler_SubscribeKvEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeKvEventsRequest, KvEventBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SglangScheduler_SubscribeKvEventsClient = grpc.ServerStreamingClient[KvEventBatch]

// SglangSchedulerServer is the server API for SglangScheduler service.
// All implementations must embed UnimplementedSglangSchedulerServer
// for forward compatibility.
//
// Service definition for SGLang scheduler communication
// This protocol bridges the Rust router and Python scheduler
type SglangSchedulerServer interface {
	// Submit a generation request (supports streaming)
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error
	// Submit an embedding request
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// Health check and metrics
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Abort a running request
	Abort(context.Context, *AbortRequest) (*AbortResponse, error)
	// Get model information
	GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error)
	// Get server information
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	// Get comprehensive load metrics
	GetLoads(context.Context, *GetLoadsRequest) (*GetLoadsResponse, error)
	// Flush the KV cache on all scheduler processes
	FlushCache(context.Context, *FlushCacheRequest) (*FlushCacheResponse, error)
	// Start the profiler on all scheduler processes
	StartProfile(context.Context, *StartProfileRequest) (*ProfileResponse, error)
	// Stop the profiler and export traces
	StopProfile(context.Context, *StopProfileRequest) (*ProfileResponse, error)
	// Get tokenizer artifacts for remote construction
	GetTokenizer(*GetTokenizerRequest, grpc.ServerStreamingServer[GetTokenizerChunk]) error
	// Subscribe to KV cache events (server-streaming)
	SubscribeKvEvents(*SubscribeKvEventsRequest, grpc.ServerStreamingServer[KvEventBatch]) error
	mustEmbedUnimplementedSglangSchedulerServer()
}

// UnimplementedSglangSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSglangSchedulerServer struct{}

func (UnimplementedSglangSchedulerServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedSglangSchedulerServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedSglangSchedulerServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSglangSchedulerServer) Abort(context.Context, *AbortRequest) (*AbortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedSglangSchedulerServer) GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedSglangSchedulerServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedSglangSchedulerServer) GetLoads(context.Context, *GetLoadsRequest) (*GetLoadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoads not implemented")
}
func (UnimplementedSglangSchedulerServer) FlushCache(context.Context, *FlushCacheRequest) (*FlushCacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushCache not implemented")
}
func (UnimplementedSglangSchedulerServer) StartProfile(context.Context, *StartProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProfile not implemented")
}
func (UnimplementedSglangSchedulerServer) StopProfile(context.Context, *StopProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProfile not implemented")
}
func (UnimplementedSglangSchedulerServer) GetTokenizer(*GetTokenizerRequest, grpc.ServerStreamingServer[GetTokenizerChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetTokenizer not implemented")
}
func (UnimplementedSglangSchedulerServer) SubscribeKvEvents(*SubscribeKvEventsRequest, grpc.ServerStreamingServer[KvEventBatch]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeKvEvents not implemented")
}
func (UnimplementedSglangSchedulerServer) mustEmbedUnimplementedSglangSchedulerServer() {}
func (UnimplementedSglangSchedulerServer) testEmbeddedByValue()                         {}

// UnsafeSglangSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SglangSchedulerServer will
// result in compilation errors.
type UnsafeSglangSchedulerServer interface {
	mustEmbedUnimplementedSglangSchedulerServer()
}

func RegisterSglangSchedulerServer(s grpc.ServiceRegistrar, srv SglangSchedulerServer) {
	// If the following call pancis, it indicates UnimplementedSglangSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SglangScheduler_ServiceDesc, srv)
}

func _SglangScheduler_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SglangSchedulerServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SglangScheduler_GenerateServer = grpc.ServerStreamingServer[GenerateResponse]

func _SglangScheduler_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_GetModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).GetModelInfo(ctx, req.(*GetModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_GetLoads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).GetLoads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_GetLoads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).GetLoads(ctx, req.(*GetLoadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_FlushCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).FlushCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_FlushCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).FlushCache(ctx, req.(*FlushCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_StartProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).StartProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_StartProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).StartProfile(ctx, req.(*StartProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_StopProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SglangSchedulerServer).StopProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SglangScheduler_StopProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SglangSchedulerServer).StopProfile(ctx, req.(*StopProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SglangScheduler_GetTokenizer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTokenizerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SglangSchedulerServer).GetTokenizer(m, &grpc.GenericServerStream[GetTokenizerRequest, GetTokenizerChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SglangScheduler_GetTokenizerServer = grpc.ServerStreamingServer[GetTokenizerChunk]

func _SglangScheduler_SubscribeKvEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeKvEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SglangSchedulerServer).SubscribeKvEvents(m, &grpc.GenericServerStream[SubscribeKvEventsRequest, KvEventBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SglangScheduler_SubscribeKvEventsServer = grpc.ServerStreamingServer[KvEventBatch]

// SglangScheduler_ServiceDesc is the grpc.ServiceDesc for SglangScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SglangScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sglang.grpc.scheduler.SglangScheduler",
	HandlerType: (*SglangSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _SglangScheduler_Embed_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _SglangScheduler_HealthCheck_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _SglangScheduler_Abort_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _SglangScheduler_GetModelInfo_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _SglangScheduler_GetServerInfo_Handler,
		},
		{
			MethodName: "GetLoads",
			Handler:    _SglangScheduler_GetLoads_Handler,
		},
		{
			MethodName: "FlushCache",
			Handler:    _SglangScheduler_FlushCache_Handler,
		},
		{
			MethodName: "StartProfile",
			Handler:    _SglangScheduler_StartProfile_Handler,
		},
		{
			MethodName: "StopProfile",
			Handler:    _SglangScheduler_StopProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _SglangScheduler_Generate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTokenizer",
			Handler:       _SglangScheduler_GetTokenizer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeKvEvents",
			Handler:       _SglangScheduler_SubscribeKvEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sglang_scheduler.proto",
}
